### ISSUE TITLE
Heavy blow/bleed bugs

### ISSUE THREAD

**Issue by ErioirE** [DistractionCrab/Charm-Crab#8] opened 2023-02-18 05:10 UTC
Bleed can cause significant issues if it kills certain bosses or during certain phases of bosses. For example, if the Collector is reduced to 0 by bleed while in his ceiling phase he will never come back down and the the script for him dying will not activate, making the encounter impossible to complete and requiring you to go rest at a bench and try the boss again.

Also, there should be a maximum number of bleed stacks/bleed damage per activation. Currently bleed + Weaversong can shred bosses faster than any other source of damage because the stacks can easily be chained with little effort. I was able to kill NKG in his FIRST balloon phase because bleed is so broken.

**Comment by DistractionCrab** [comment] 2023-02-18 11:37
I'll look into the collector issue; That's an enemy specific thing I'll have to track down and see when best to identify the state transitions.

As for NKG, the balloon thing isn't as impressive as it sounds; their AI isn't a strict percentage of health based off a maximum and because of that their balloon phases all happen towards the very end of the fight regardless. However, if this kill is happening fast (i.e. say within 5 seconds, this is an issue), so feel free to let me know the fastest kill you got with this setup time-wise, not phase-wise.

**Comment by DistractionCrab** [comment] 2023-02-21 21:09
Alright, I've tried something that should deal with the collector issue (just not having bleed tick when they're invincible).

As for NKG, let me know what a kill time for it is, because the only way you're killing NKG with bleed really fast is if their health isn't getting set correctly, which is a bug to fix. Other than that, bleed isn't going to do over 10k damage extremely unless you're stacking it close to 100 times, which would be a feat of the player themselves.

I will look into making the balloon phases more natural with the improved health. In meantime I'll leave this issue open until further information comes in or I've resolved what I can see are issues.

**Comment by ErioirE** [comment] 2023-02-22 00:40
Also, I ran into issues similar to the Collector bug for the pantheon bossfights for the nailmaster brothers and False knight/Failed champion.

**Comment by ErioirE** [comment] 2023-02-22 00:43
After thinking about it more I think the NKG really fast kill was caused because of using a charm from the Transcendance mod, which gave double summons + weaversong, so there were 6 weaverlings instead of 3 and that probably was why it stacked the bleed so fast.

**Comment by DistractionCrab** [comment] 2023-02-22 19:52
The False knight I'm aware of; It has the same issues as NKG, in that when the phase transitions (or rather built in AI) puts the health as a predetermined value not a "maximum value." So that's something I've been meaning to deal with, just never got around to it.

**Comment by DistractionCrab** [comment] 2023-02-23 12:54
Adding an Update to this issue, which has a weird reason why it's happening that I didn't expect.

- NKG/TMG: Phase transitions have been updated to be at quarter health according to scaled reason.
-  Bleed stacks a lot because for some reason grim is constantly colliding with the weaverlings, even when extremely far away (this is a weird game bug, so something I have to figure out why this weird collisions happens).
- The overall damage you were seeing was due to this most likely, getting 50+ stacks very quickly is not intended and shouldn't be happening.
-  False Knight is being worked on for HP resets, each instance is slightly different, but the non-GG versions have a value that can be modified, but GG versions do not so this will take longer to fix/update.

So we discovered something really weird; Also transcendence probably didn't help with the issues, but isn't the cause of it definitely. But I'll keep this updated as more info arises/fixes happen.

**Comment by DistractionCrab** [comment] 2023-02-24 11:15
I've put out an update (v1.0.3) which should address the things in here. Update notes are on the release page, but should handle the concerns here. 

Will close this in a bit once the update is pushed to Scarab and there's no further concern.

**Closed** 2023-03-05 10:34 UTC
